version: "3"
services:
  service.app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:5000"
    networks:
      - bilibili_net

  service.db:
    image: "mongo:latest"
    networks:
      - bilibili_net
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - bilibili_data:/data/db

volumes:
  bilibili_data:
networks:
  bilibili_net: